### ISSUE TITLE
Average Speed wrong calculated within Statistics View

### ISSUE THREAD

**Issue by pascalbrunner** [jovandeginste/workout-tracker#100]
Hi, 

I just updated to the newest Version and now my average speed is not correct anymore (it is a little to high)

**Comment by wills106** [comment]
Might be helpful if you can share some screen shots or data of the discrepancy.

On the Individual workout I'm within 0.06 Mph between workout-tracker and FitoFit. Garmin Connect is different again slightly. Probably down to how individual apps round the values.

**Comment by pascalbrunner** [comment]
![screenshot1](https://github.com/jovandeginste/workout-tracker/assets/59732414/c3a4e57d-31d9-4b5d-83eb-7f98356a31f9)
![screenshot2](https://github.com/jovandeginste/workout-tracker/assets/59732414/b6891db6-b01e-4b56-ad88-4b119b8057af)

My average speeds were correct last time I checked. After updating it now shows 12 km/h average, but my actual runs in march were slower (shown in red box)

**Comment by jovandeginste** [comment]
Its the "max" of the "averages", if you follow ... should it actually be the average of the averages?
