### ISSUE TITLE
Option to show actual date instead of relative from current time

### ISSUE THREAD

**Issue by nrevolt** [jovandeginste/workout-tracker#127]
Would be nice to have an option to switch the date displayed.

In Workouts view, and when viewing a specific workout, the date is shown relative to the current time, e.g. 3 days, 1 hour ago instead of 2024-04-15 1:31 PM.

Great work overall, thank you.

**Comment by jovandeginste** [comment]
If you hover, it shows the actual date; would you like an option to switch that behavior?

**Comment by nrevolt** [comment]
Awesome, thanks for the update!
