### ISSUE TITLE
Total statistics are empty

### ISSUE THREAD

**Issue by Thovi98** [jovandeginste/workout-tracker#129]
Hey, thanks for this app!
Works great!

I have an issue with the global statistics above, they are empty althought a track has been uploaded.
![Capture](https://github.com/jovandeginste/workout-tracker/assets/51749973/dff5d26d-22aa-4d33-8ebd-b6c728c1c629)

By the way, were are stored the uploaded track on the server? I couldn’t find it in workout-tracker directory (but I can download it from the web interface).

Is there a way to choose a data directory (and set it as environment variable?). It would be useful for [the package I made for Yunohost](https://github.com/YunoHost-Apps/workout-tracker_ynh/). Thanks!

**Comment by wills106** [comment]
The workouts are stored in a Database in /data

If you used Docker did you map /data to a local folder?

**Comment by Thovi98** [comment]
Thanks for your input!
I forgot to say that I don’t use docker, I installed [natively](https://github.com/jovandeginste/workout-tracker?tab=readme-ov-file#natively).

**Comment by jovandeginste** [comment]
The totals above default to running; you can change this in your profile settings (click on your username in the top menu) 

The workouts are saved in the database. Natively, the database is stored in the location from where you run the binary (this is not per se the location where you _saved_ the binary!)

**Comment by Thovi98** [comment]
Thank you! Okay it works!

Si it would be nice to
- explain on the dashboard for which sports are those stats;
- be able to show all stats from all sports.

Ne pressure tho 😇

And I understand now why I couldn't find uploaded files as it is in the database, thank you!

**Comment by jovandeginste** [comment]
I'll add some cue as to which totals are shown, and some kind of auto-logic to (default) show workout totals for workout type with highest count.
