### ISSUE TITLE
Add equipment

### ISSUE THREAD

**Issue by DavidHenryThoreau** [jovandeginste/workout-tracker#135]
It would be nice to add equipments like bike, shoes, bag

**Comment by jovandeginste** [comment]
Would this not fit in the "notes" field? Or how should I see this?

**Comment by DavidHenryThoreau** [comment]
It may be interesting to add equipment entry in the database in order to get stats like FitTrackee does, see https://github.com/SamR1/FitTrackee/issues/259 , for example to know how many km you're running with shoes, km with that bike..
