### ISSUE TITLE
docker image as non-root user

### ISSUE THREAD

**Issue by DavidHenryThoreau** [jovandeginste/workout-tracker#136]
Inside the docker image the app seems to run as root user:

```
docker exec -it workout-tracker sh
/data # ps -ef|grep workout
    1 root      0:00 /app/workout-tracker
   20 root      0:00 grep workout
```
Maybe it would be great to create a user with less privileges ?

**Comment by jovandeginste** [comment]
You can pass the `-u` flag to `docker run`; if the volume is writable for that user, everything should work (you may need to use an unprivileged port too)

**Comment by jovandeginste** [comment]
Yes that's how linuxserver build their images; I have nothing against it, but seems like an extra layer which is not per se necessary...
