### ISSUE TITLE
Error when enabling API access: constraint failed: UNIQUE constraint failed: profiles.id (1555) 

### ISSUE THREAD

**Issue by tjhowse** [jovandeginste/workout-tracker#139]
I tried to enable the API access so I could integrate directly with fitotrack

![image](https://github.com/jovandeginste/workout-tracker/assets/1008081/adc60522-135a-45b2-8721-7f9b8b00c6c7)
![image](https://github.com/jovandeginste/workout-tracker/assets/1008081/4b1c03db-ad68-4251-80df-850677d1dda1)

Browser error: Something went wrong: constraint failed: UNIQUE constraint failed: profiles.id (1555) 
Logs:
```
workout_tracker                   | {"time":"2024-05-03T01:04:08.819639955Z","level":"ERROR","msg":"constraint failed: UNIQUE constraint failed: profiles.id (1555)","app":"workout-tracker","version":"master","sha":"<snip>","module":"database","error":"constraint failed: UNIQUE constraint failed: profiles.id (1555)","query":"INSERT INTO `profiles` (`created_at`,`updated_at`,`deleted_at`,`user_id`,`api_active`,`language`,`totals_show`,`timezone`,`auto_import_directory`,`socials_disabled`,`prefer_full_date`,`preferred_units`,`id`) VALUES (\"2024-05-03 01:04:08.818\",\"2024-05-03 01:04:08.818\",NULL,1,true,\"browser\",\"auto\",\"\",\"\",false,false,\"{\"\"speed\"\":\"\"\"\",\"\"distance\"\":\"\"\"\",\"\"elevation\"\":\"\"\"\"}\",3) RETURNING `id`","duration":1465174,"rows":0,"file":"/app/pkg/database/profile.go:64"}
```
Version:  branch master (5ccfa422)
Environment: Containerised, Debian 12 64b, image from ghcr.io/jovandeginste/workout-tracker:master
Sqlite:
```
sqlite> select * from profiles;
id|created_at|updated_at|deleted_at|user_id|api_active|language|totals_show|timezone|auto_import_directory|socials_disabled|prefer_full_date|preferred_units
1|2024-03-08 12:44:45.089166958+00:00|2024-03-08 12:44:45.089166958+00:00||0|0|browser|running|||||
2|2024-03-08 13:06:39.760551862+00:00|2024-03-08 13:06:39.760551862+00:00||0|0|browser|running|Australia/Brisbane||||
```

This may be a DB schema issue, since I originally set up the DB on a much earlier version. I am perfectly amenable to deleting the database and re-importing the track files, but I thought the above might be useful.

**Comment by jovandeginste** [comment]
I'll try to look into this soon, but it's hectic at the moment :)

**Comment by jovandeginste** [comment]
Sorry this took a while... Thanks for reporting!
