### ISSUE TITLE
Add Translations for German

### ISSUE THREAD

**Issue by GhostsiderM** [jovandeginste/workout-tracker#15]
So far there is only english and dutch.
It would be great if there was also a choice of German as a translation.

If you want, I can also do this.

**Comment by jovandeginste** [comment]
My German is rubbish, so please! I could ask ChatGPT, but I would prefer a human. I saw how it translated the Dutch: 96% was good, 2% were really awful...

Will the JSON file work, or is there a better way?

**Comment by jovandeginste** [comment]
I created a project here: https://crowdin.com/project/workout-tracker
No idea how good it works. Let's find out!

**Comment by GhostsiderM** [comment]
well I will enter everything there as version 1.
If you then make an update I can check everything and refine it further.

**Comment by jovandeginste** [comment]
Should be merged in master - please test!

**Comment by GhostsiderM** [comment]
Thank you that it worked out so quickly.
When I make adjustments to the translation, do you always merge it into the latest master?

One more point. Under workouts/add and then type, the types are in English instead of the selected language.

**Comment by jovandeginste** [comment]
I will periodically merge into master; however, you may build the server yourself with your changes, to test the translations?

**Comment by GhostsiderM** [comment]
I use the docker compose variant. Then I'll have to try it out myself and see how I get it to work.

**Comment by jovandeginste** [comment]
Everything should be present to build the Docker image from scratch, with `make build-docker`; you should point your compose file to the new image name, however. I use a test-setup (with a separate database) for these things.

**Comment by jovandeginste** [comment]
I will close this issue; if you find any issues with building Docker images (or translations), feel free to open a new issue!
