### ISSUE TITLE
How to Activate User?

### ISSUE THREAD

**Issue by iSAT32196** [jovandeginste/workout-tracker#166]
Hello!

Sorry this might be a super basic question, but I see in the instructions it says new users need to be activated, but I'm not sure how? So far I have installed workout-tracker via docker compose, put in my info to "Sign up", and I'm not sure what to do next?

**Comment by iSAT32196** [comment]
I have figured it out I think! Reading more, I saw that there was a default user with login admin admin, which seems to have let me in and I can activate my account. Should be all set!

**Comment by jovandeginste** [comment]
Great you find the solution!
