### ISSUE TITLE
Feature Idea: Hiking or Custom Types

### ISSUE THREAD

**Issue by iSAT32196** [jovandeginste/workout-tracker#167]
I was wondering if it's either possible or would be possible to either make custom categories for workouts or to add "hiking" as an option? For now I can put things under "walking" but, I know for me at least, there's some differences when I would consider a workout as walking or hiking.

**Comment by jovandeginste** [comment]
I'll add hiking as a without type; I'm also working on a more generic way to add many custom types..

**Comment by iSAT32196** [comment]
Okay awesome thank you!

**Comment by jovandeginste** [comment]
See #169 for hiking

**Comment by iSAT32196** [comment]
Awesome thank you!

**Comment by iSAT32196** [comment]
Sorry, one last thing, is there an easy way to update the program so to not lose the data that's been imported, or do I just reinstall it?

**Comment by jovandeginste** [comment]
did you provide a volume in your compose file?

**Comment by iSAT32196** [comment]
Sorry, I'm a bit confused on the question - so far all I've done are these steps:

# Download the compose.yaml
curl https://raw.githubusercontent.com/jovandeginste/workout-tracker/master/compose.yaml --output compose.yaml

# Start the server
docker compose up -d

**Comment by jovandeginste** [comment]
If you used the suggested [`compose.yaml`](https://github.com/jovandeginste/workout-tracker/blob/master/compose.yaml), you should have a folder `data` in the folder where you put the `compose.yaml` - this folder contains the database.

If you want to update, you can run `docker compose pull` to fetch the latest version, and `docker compose up -d` to restart the container (with the new image, and the saved database)

**Comment by jovandeginste** [comment]
You are not (yet) running the latest version; according to the version string, you are still on the build from June 4th (you can hover over the version and see the build time).

I'm not sure what exactly went wrong. Can you provide me the output from:

`docker images | grep workout`

and

`docker ps | grep workout`

(Be sure to double check it does not contain any sensitive information)

Also, no need to `stop` the container beforehand.

**Comment by iSAT32196** [comment]
Yeah sure! I believe I took out the sensitive info

![workout tracker grep workout jpg](https://github.com/jovandeginste/workout-tracker/assets/5175564/4e6ee50b-b4d2-4760-b67f-300980f7d245)

**Comment by jovandeginste** [comment]
You seem to have the latest image downloaded, but perhaps the restart did not work (it is still using the older image).
I use this command: `docker compose up --detach --remove-orphans --wait`

**Comment by iSAT32196** [comment]
Sure! Doesn't seem to have done much. I also double checked to see if maybe I was somehow running two instances of workout-tracker. Earlier before I put in the comment about updating, I had stopped workout tracker, copied the data folder elsewhere, removed the .yaml file and reinstalled using the original instructions, then copied the data folder back in. So I thought maybe I had accidentally left an old version running in docker or something, but no seems like it's still just the one running.

The hiking option is still not there and if I mouse over the branch master bit at the bottom of the page, it says "Build time 2024-06-04"

![Workout tracker remove orphans edited](https://github.com/jovandeginste/workout-tracker/assets/5175564/d13037d1-a0a1-413f-9b05-9260fec3394b)

**Comment by jovandeginste** [comment]
Can you copy the content of `compose.yaml`?

**Comment by jovandeginste** [comment]
Or, force a restart: `docker compose rm -v --force --stop`, then `docker compose up -d`

**Comment by iSAT32196** [comment]
Sure! I forced the restart, still no luck. 

![Workout Tracker Force restart edited](https://github.com/jovandeginste/workout-tracker/assets/5175564/ba2afbac-3bc9-4952-885e-449f91222a2e)

And then here is the compose.yaml file:

version: "3.8"
services:
  workout-tracker:
    image: ghcr.io/jovandeginste/workout-tracker:master
    restart: unless-stopped
    ports:
      # Host Port:Container Port
      - 8080:8080
    volumes:
      - ./data:/data
    environment:
      - WT_JWT_ENCRYPTION_KEY=my-secret-key

**Comment by jovandeginste** [comment]
And the output of `docker ps` now?

**Comment by iSAT32196** [comment]
Here you go!

![workout tracker docker ps edited](https://github.com/jovandeginste/workout-tracker/assets/5175564/63f9928b-6e65-4ef6-833c-303493cf5b8b)

**Comment by jovandeginste** [comment]
It seems your container is never actually removed. Can you run the `rm` command, and then paste the output of `docker ps -a | grep workout` ?

**Comment by iSAT32196** [comment]
sure so just run `docker compose rm` ?

**Comment by jovandeginste** [comment]
yes

**Comment by iSAT32196** [comment]
Here you go! It looks like I had to stop it first to run the rm command? But after that it says it removed, but as you see still lists something:

![workout tracker docker compose rm edited](https://github.com/jovandeginste/workout-tracker/assets/5175564/1388ab20-27b2-4d54-a7f2-d19f87947f53)

**Comment by jovandeginste** [comment]
Yes, you need to add the `--force` flag for that.

You seemed to have an old container remaining; this should not be an issue, but you can remove it anyway: `docker container prune` will take care of that.

Then rerun `docker ps -a` and verify no stopped or exited containers remain, and nothing matching workout-tracker.

Then run `docker compose up` again and paste the output of `docker ps -a | grep workout`.

**Comment by iSAT32196** [comment]
Okay got it! 

When I first ran the 'docker compose up' command I didn't add the -d and so the window stayed open and kept repeating the lines below every now and then. Wasn't sure how to stop it:

![workout tracker docker prune 1 edited](https://github.com/jovandeginste/workout-tracker/assets/5175564/c3ebf27c-0ee9-4e1a-a03d-5e38a4bbed86)

So ended up running the steps again using the 'docker compose up -d' command and that got it to work, and now I see hiking as an option! Thank you so much!

![workout tracker docker prune 2 edited](https://github.com/jovandeginste/workout-tracker/assets/5175564/4680ba70-ede6-4e68-9f4f-4648da572164)

**Comment by jovandeginste** [comment]
That explains a lot! Happy you got it solved...!

**Comment by iSAT32196** [comment]
Yeah thanks for walking me through it!
