### ISSUE TITLE
Inconsistencies with time

### ISSUE THREAD

**Issue by Fudgeey** [jovandeginste/workout-tracker#17]
Hello,
I have imported a bunch of workouts, but the calendar is displaying the timing of one of them wrong. I assume its basing it off UTC and has meant a workout I did during the day is over two days now.

Here is the calendar showing its over two days:
![image](https://github.com/jovandeginste/workout-tracker/assets/32042040/e623ed14-2caf-4f1c-8b55-fe543f1d4585)

Here is the average speed / elevation graph showing the correct times at the bottom:
![image](https://github.com/jovandeginste/workout-tracker/assets/32042040/6841ab76-0e07-4f86-bc45-d4b74c82e124)

Just want to say thanks for making this, amazing project so far!

**Comment by jovandeginste** [comment]
Are you running the service as a docker container? If so, would you mind adding an environment variable `TZ=your/timezone`? Just to check if it is indeed timezone related...

**Comment by jovandeginste** [comment]
As for an actual answer: I believe I need to add a "timezone" option to a user's profile, so I can merge the different ways I localize times into a single consistent way...

**Comment by Fudgeey** [comment]
Sweet, looks like setting the timezone worked! Thanks.
![image](https://github.com/jovandeginste/workout-tracker/assets/32042040/42ccb8d7-046a-44c3-8af8-30ac495cf987)

**Comment by jovandeginste** [comment]
Could you try with the latest master image, without the TZ env var? You should set the timezone for your account via the web interface after updating.

**Comment by Fudgeey** [comment]
Yep! That all works fine now! Thanks.
