### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by mcrummett** [jovandeginste/workout-tracker#173]
Minor request: ability to change "date" column so it shows the date of the workout rather than time since the workout

**Comment by jovandeginste** [comment]
There is an option in your profile to switch this

**Comment by mcrummett** [comment]
Well thanks embarrassing 😂
    Sent from Outlook for iOS
  

 From: Jo Vandeginste ***@***.***>Sent: Friday, June 14, 2024 19:47To: jovandeginste/workout-tracker ***@***.***>Cc: mcrummett ***@***.***>; Author ***@***.***>Subject: Re: [jovandeginste/workout-tracker] Feature Request (Issue #173) 
There is an option in your profile to switch this

**Comment by jovandeginste** [comment]
No worry
