### ISSUE TITLE
Default path to swagger API documentation

### ISSUE THREAD

**Issue by theowoo** [jovandeginste/workout-tracker#183]
Hi, what is the default path to the swagger API documentation? I have enabled API for my user but kept running into 404. Thanks.

**Comment by jovandeginste** [comment]
It is in the code repository, not served by the binary.

**Comment by jovandeginste** [comment]
You can access it via https://editor.swagger.io/, file, import URL, <https://raw.githubusercontent.com/jovandeginste/workout-tracker/master/docs/swagger.yaml>

**Comment by theowoo** [comment]
Thank you!
