### ISSUE TITLE
Automatic detection of workouts and metrics differences

### ISSUE THREAD

**Issue by muzzah** [jovandeginste/workout-tracker#184]
Hey

Nice project! Thanks for your efforts. I imported my 300+ apple fitness workouts that are made up mainly of running, hiking, walking workouts. Everything is automatically detected as either running or walking. The hikes are I assume categorised as walking workouts. I guess its not easy to differentiate between the two without specific signals. Im also seeing a bit of a discrepency between what apple fitness metrics and what the this web app shows.

Im assuming the iOS device uses different ways to calculate some of these metrics vs using purely the GPX file data. Is this a known issue?

**Comment by muzzah** [comment]
Btw, if you want a walking based gpx file and a running one to compare and test with I can send it to you personally rather than attach it here as it contains location info I dont want to share publicly.

**Comment by jovandeginste** [comment]
There is no hint as to which type of activity was tracked in this gpx (unless the other files contain anything useful?)

This means we can only infer based on speed, which is what we do so far.

You can change the type after uploading. 

You see any other solution?

**Comment by jovandeginste** [comment]
I will close this for now, let me know if you have any ideas!

**Comment by muzzah** [comment]
I think the only way to do this with GPX files like the one apple produces is to use historical data and create a model based on other workouts. Otherwise it would be difficult. All good. Thanks for looking into it.
