### ISSUE TITLE
Time Offset from GMT seems wrong.

### ISSUE THREAD

**Issue by TheBig-O** [jovandeginste/workout-tracker#226]
Not sure why, but when I upload a GPX file, the timezone offset seems off. I'm -4 from GMT. The time of my run was 17:37 but it shows up in the tracker as 13:37. When I try to update it, the the workout reverts to the 13:37 time.
Is this the result of the GPX offset not registering the UTC offset? Is there a way to override this?

**Comment by jovandeginste** [comment]
Can you confirm by checking the gpx file? It should have multiple times, perhaps at the top, but at least per registered point too.

**Comment by TheBig-O** [comment]
This is the extract from the first few elements and the closing tags. Times seem to show correctly for Zulu time.
```
<?xml version="1.0" encoding="UTF-8"?>
<gpx creator="HealthFit" version="1.1"
xsi:schemaLocation="http://www.topografix.com/GPX/1/1
http://www.topografix.com/GPX/11.xsd"
xmlns:gpxtpx="http://www.garmin.com/xmlschemas/TrackPointExtension/v1"
xmlns="http://www.topografix.com/GPX/1/1"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xmlns:gpxx="http://www.garmin.com/xmlschemas/GpxExtensions/v3">
	<trk>
		<type>running</type>
		<trkseg>
			<trkpt lat="REMOVED" lon="REMOVED">
				<ele>39.916835</ele>
				<time>2024-08-03T21:37:43.000Z</time>
				<extensions>
					<gpxtpx:TrackPointExtension>
						<gpxtpx:hr>125</gpxtpx:hr>
						<gpxtpx:cad>75</gpxtpx:cad>
						<gpxtpx:course>29.955985</gpxtpx:course>
						<gpxtpx:hAcc>2.266727</gpxtpx:hAcc>
						<gpxtpx:vAcc>1.574546</gpxtpx:vAcc>
					</gpxtpx:TrackPointExtension>
				</extensions>
			</trkpt>
			<trkpt lat="REMOVED" lon="REMOVED">
				<ele>39.870714</ele>
				<time>2024-08-03T21:37:44.000Z</time>
				<extensions>
					<gpxtpx:TrackPointExtension>
						<gpxtpx:hr>125</gpxtpx:hr>
						<gpxtpx:cad>75</gpxtpx:cad>
						<gpxtpx:course>30.739459</gpxtpx:course>
						<gpxtpx:hAcc>2.013742</gpxtpx:hAcc>
						<gpxtpx:vAcc>1.384886</gpxtpx:vAcc>
					</gpxtpx:TrackPointExtension>
				</extensions>
			</trkpt>
			<trkpt lat="REMOVED" lon="REMOVED">
				<ele>39.829204</ele>
				<time>2024-08-03T21:37:45.000Z</time>
				<extensions>
					<gpxtpx:TrackPointExtension>
						<gpxtpx:hr>128</gpxtpx:hr>
						<gpxtpx:cad>75</gpxtpx:cad>
						<gpxtpx:course>25.123236</gpxtpx:course>
						<gpxtpx:hAcc>1.864349</gpxtpx:hAcc>
						<gpxtpx:vAcc>1.235426</gpxtpx:vAcc>
					</gpxtpx:TrackPointExtension>
				</extensions>
			</trkpt>
...
				<extensions>
					<gpxtpx:TrackPointExtension>
						<gpxtpx:course>198.625878</gpxtpx:course>
						<gpxtpx:hAcc>2.397099</gpxtpx:hAcc>
						<gpxtpx:vAcc>1.340887</gpxtpx:vAcc>
					</gpxtpx:TrackPointExtension>
				</extensions>
			</trkpt>
		</trkseg>
	</trk>
</gpx>
```

**Comment by wills106** [comment]
This is the same as #75 
![image](https://github.com/user-attachments/assets/97f75c35-e499-4a7d-b030-f3f0423148e6)
That walk was done at 12:09 BST not 11:09

**Comment by JPDVM2014** [comment]
I'm having the same issue. My .gpx file has my correct local time with the -4 offset, but Workout Tracker adds another -4 offset. If I set Workout Tracker to GMT time, the workout times are correct.

If it helps, I'm using .gpx files from OpenTracks.

**Comment by jovandeginste** [comment]
The problem with times is there are so many points where this is parsed and can go wrong...:

- the GPX file
- the server hosting the workout tracker
- the browser
- the setting in the profile

Can you check & report all those settings?

Do I understand correctly, that some GPX files record the times in the local timezone?

**Comment by wills106** [comment]
I can understand why it's difficult. Time is a pain, especially with Summer / Winter time.

Just had a look at my GPX from lunchtime.
Local time was 12:02 BST (British Summer Time) ie GMT +1
But GPX is 2024-09-13T11:02:27Z ie GMT 0
But when viewed in FitoTrack it displays as 12:02, so it must be taking into account that the phone / app know it's BST at the moment.

**Comment by jovandeginste** [comment]
> I can understand why it's difficult. Time is a pain, especially with Summer / Winter time.
> 
> Just had a look at my GPX from lunchtime. Local time was 12:02 BST (British Summer Time) ie GMT +1 But GPX is 2024-09-13T11:02:27Z ie GMT 0 But when viewed in FitoTrack it displays as 12:02, so it must be taking into account that the phone / app know it's BST at the moment.

So far so good, the data matches "reality"; now the other settings: server, browser and profile?

**Comment by wills106** [comment]
As per #75 my browser is:
![image](https://github.com/user-attachments/assets/d0e45340-94c6-4456-ae2e-29e88259de77)

Server:
![image](https://github.com/user-attachments/assets/c4435a3e-d2c5-4e70-8d4e-a7354bba0735)

As I post this it's 19:07

**Comment by jovandeginste** [comment]
I made another attempt at fixing this timezone issue; could you try this out?

**Comment by wills106** [comment]
It seems to be correct, from what I can see.

Thanks for working on this.
