### ISSUE TITLE
Can't evaluate field "Filename"

### ISSUE THREAD

**Issue by Firesphere** [jovandeginste/workout-tracker#238]
On a brand new installation, after importing 230~ish trips, I get the following error when I want to see the details of a workout:
```
{
  "time": "2024-08-12T03:50:06.587651094Z",
  "method": "GET",
  "host": "workout.example.com",
  "path": "/workouts/232",
  "query": "",
  "params": {
    "id": "232"
  },
  "route": "/workouts/:id",
  "ip": "1.2.3.4",
  "referer": "https://workout.example.com/",
  "length": 0
},
"response": {
  "time": "2024-08-12T03:50:06.596243524Z",
  "latency": 8592470,
  "status": 500,
  "length": 0
},
"error": {
  "code": 500,
  "internal": {
    "Name": "workouts_show.html",
    "Err": {}
  },
  "message": "Internal Server Error"
},
"internal": "template: workouts_show.html:31:30: executing \"workouts_show.html\" at <.Filename>: can't evaluate field Filename in type *database.Workout"
}
```

**Comment by jovandeginste** [comment]
Can you confirm which version you are running?

**Comment by Firesphere** [comment]
Docker latest

**Comment by jovandeginste** [comment]
At the bottom of the page is a version; can you confirm the exact version?

**Comment by Firesphere** [comment]
Yep, sure thing!
Version: Workout Tracker, v1.18.0 (e8ce84fd)
Environment: Docker
Docker image release: ghcr.io/jovandeginste/workout-tracker:latest
Docker image pull date: Mon Aug 12 2024 02:48:16 GMT+0000
Server: ARM64
Host OS: Ubuntu 22.04.4/aarch64-minimal

**Comment by jovandeginste** [comment]
There was a race condition when publishing the docker image; I made a release with the bug fixed, but too short after the release _with_ the bug.

I re-built the image. Can you pull & try again?

**Comment by Firesphere** [comment]
That solved it, epic, thanks!
Closing this as solved and blame bad luck happens sometimes :)
