### ISSUE TITLE
Cannot de-select equipment

### ISSUE THREAD

**Issue by TheBig-O** [jovandeginste/workout-tracker#240]
I have a pair of shoes that are related to a variety of workouts but are marked as "inactive." 
Every time I add a new workout, they are added as equipment, which I don't want. 
When I try to de-select the default activities in the editing screen, they come right back when I click update.
The behavior I would have expected is that when the equipment is not active, it is not added to a workout. However, if all I have to do is de-select the default activities, that works too.

  
<img width="1153" alt="image" src="https://github.com/user-attachments/assets/5e792d9e-3641-46ec-bba1-273eee5fe9aa">

<img width="1153" alt="image" src="https://github.com/user-attachments/assets/0de50d7b-b48f-4ab5-b349-201a977850e8">

**Comment by jovandeginste** [comment]
The bug was only when the default workout type list was empty (because then you don't get a form field...)

It should now be fixed, anyway.
