### ISSUE TITLE
I miss the Detail-Based filtering

### ISSUE THREAD

**Issue by lukasitaly** [jovandeginste/workout-tracker#242]
I updated workout-tracker and since I updated it I can't filter by distance or duration in the workouts tab. Has this been intentionally removed?

**Comment by jovandeginste** [comment]
If you mean sorting: this was no longer fitting because of the addition of other types of workouts. I changed the separate columns for distance etc to a single "details" column with information depending on the workout type.

The plan is to add an actual filter/sort function.

**Comment by lukasitaly** [comment]
Yea I meant sorting sorry. Ok awesome, I'm looking forward to it! Thanks for the quick reply! :)
