### ISSUE TITLE
Rate limit when uploading multiple workouts

### ISSUE THREAD

**Issue by pixelspark** [jovandeginste/workout-tracker#250]
When uploading a bunch of GPXes at the same time through 'Add workout', I get many 'rate limited' messages:

````
3:50PM WRN Rate limited - waiting 760.462166ms app=workout-tracker version=segments sha=716cc15276f411f46625f5564b6d2651eee3bcb8 module=app
````

I understand this is useful, however I would expect these routes to be put in some sort of queue for deferred processing.

**Comment by jovandeginste** [comment]
I just added some UI to show when this would be happening, so we should be able to do exactly this.
