### ISSUE TITLE
Alignment of columns in tables

### ISSUE THREAD

**Issue by pixelspark** [jovandeginste/workout-tracker#257]
The columns in some tables are not _quite_ aligned, which makes them look a bit cluttered and difficult to compare rows. This first example is _almost_ okay, it just looks a bit messy:

<img width="567" alt="image" src="https://github.com/user-attachments/assets/199d8a9e-f876-402b-a128-5a6812cae8be">

The next example however is not so great:

<img width="753" alt="image" src="https://github.com/user-attachments/assets/b0233d28-93e0-4dc5-a07c-f2da99174632">

I'd just put the different values in separate `<td>`s.  However, if you like the current style visually, an easy fix is setting a min-width on the labels so they line out most of the time.

Another thing to consider, which I think is even better, is setting a `max-width` on the labels/`<td>`s.  I'd then add this CSS (I am not familiar with Tailwind but it probably has something for this):

````css
max-width: 123px;
overflow: hidden;
white-space: nowrap;
text-overflow: ellipsis;
````

This will make longer texts be cut off nicely. To make it really good, add a `<td title="full text in the td">` title attribute, so you can read all of the text while hovering 💯

**Comment by jovandeginste** [comment]
I made a PR which mostly addresses this - can you check it out (together with the other changes in master)
