### ISSUE TITLE
Feature idea: Fullscreen map

### ISSUE THREAD

**Issue by mkj0** [jovandeginste/workout-tracker#259]
Hi.

Really appreciating this project since Tomtom turned off the service for their sports watches. I'm managing to get more life out of my still working Tomtom Adventurer as a result. :-)

A couple of relatively minor things I do miss is the ability to maximise the map and switch to a satellite view - if I'm exploring somewhere new on my road bike, it's nice to be able to have a good look at the side roads and paths I missed, to see if they're worth going back and exploring further.

Cheers,

Mike

**Comment by jovandeginste** [comment]
After doing some search, osm does not provide aerial images themselves. This would require integrating another service (bing is suggested, or Esri)

Maximize the map should be easy, however.

**Comment by jovandeginste** [comment]
I managed to add Esri, and some basic full-width button

**Comment by mkj0** [comment]
Very nice, and useful in it's current form. Thanks! :-)
