### ISSUE TITLE
Add Persian to Weblate

### ISSUE THREAD

**Issue by Monirzadeh** [jovandeginste/workout-tracker#267]
Hi
can you please add Persian to weblate languges?

**Comment by jovandeginste** [comment]
Please help translating: https://hosted.weblate.org/projects/workout-tracker/web-interface/fa/

**Comment by jovandeginste** [comment]
All PR's are welcome; I have no concrete roadmap and  no matrix room yet. Maybe I should enable discussions on the project...

**Comment by jovandeginste** [comment]
I merged the Persian translation, it's now building.

**Comment by jovandeginste** [comment]
There is now a matrix room :grin: https://matrix.to/#/#workout-tracker:matrix.org

**Comment by jovandeginste** [comment]
> maybe not bad to add to Readme too

It is added, as a badge on top; I will add more explicitly
