### ISSUE TITLE
Records showing km/h no matter which unit is selected

### ISSUE THREAD

**Issue by JPDVM2014** [jovandeginste/workout-tracker#294]
My statistics on the home page show my pace as km/h no matter which unit is selected. The run details page is correct though. 

I only wish my pace was this fast. 

![Screenshot_20240910_200137_Vivaldi.jpg](https://github.com/user-attachments/assets/098e5bb9-7f15-4f66-b19d-f70ee3f07765)

**Comment by jovandeginste** [comment]
You mean min/km of course; I see

**Comment by JPDVM2014** [comment]
Yea, min/km sorry about that. It's working great now, thanks!
