### ISSUE TITLE
Support fit 2.0 format

### ISSUE THREAD

**Issue by cutec-chris** [jovandeginste/workout-tracker#316]
seems to be not supported

**Comment by fyksen** [comment]
The dependency that workout-tracker is using for .fit files is [tormoder/fit](https://github.com/tormoder/fit) , it is not actively maintained anymore.

For fit 2.0 to work, the project needs to change to a new dependency. Maybe [muktihari/fit](https://github.com/muktihari/fit) is a good fit (pun intended?).

**Comment by jovandeginste** [comment]
I switched to the other library - please report with your experiences!
