### ISSUE TITLE
FR: Track heart rate data

### ISSUE THREAD

**Issue by profucius** [jovandeginste/workout-tracker#318]
I would like to be able to track heart rate data in your app. TCX files can include heart rate data. I can imagine the ability to track HR data over time, to see a trend of the heart becoming healthier. One might argue that improving heart health is one of the primary reasons for tracking workout data at all.

Perhaps as a starting feature, we could import min and max HR ranges, which my workout app tracks. Then eventually use TCX type data for tracking HR by the second/minute.

If you'd like for me to provide a TCX file as an example I can do so upon request.

**Comment by jovandeginste** [comment]
The app already tracks this in gpx files; please provide a sample tcx file (you can mail it if you want to protect your privacy)

**Comment by profucius** [comment]
Apologies, I did not see that WT could process the heart rate data from a TCX file. 

Relevant: I'm having an issue importing a TCX file int WT. This file is generated by the fitness watch app that I use called Notify for Xiaomi. This same app exports GCX files and FIT files too, which WT imports successfully, so I am not sure why this filetype is failing.

Error:
`Encountered 1 problems while adding workouts: could not convert data to a GPX structure: strconv.ParseFloat: parsing "": invalid syntax`

Here is the TCX file attached. I've zeroed out every reference of GPS coordinates before uploading.
[workout.zip](https://github.com/user-attachments/files/17535514/workout.zip)

**Comment by alternativesurfer** [comment]
Hi!

I have a similar/related issue.
TCX exports from Strava include HR data. If I import them into WT, heart rate data appears as null.

If I convert the TCX to a GPX, heart rata data is present and appears correctly in WT.
What is an email I can send the TCX to?

**Comment by jovandeginste** [comment]
My GitHub committer address

**Comment by profucius** [comment]
Was my TCX file of any use?

**Comment by alternativesurfer** [comment]
> My GitHub committer address

Thank you!
Sent!

**Comment by jovandeginste** [comment]
I finally found time to take a look; this will be merged into master soon.

Re: the file uploaded here: since all points have coördinates (0, 0), they are skipped in the parser...

**Comment by jovandeginste** [comment]
@profucius please take a look at your exported TCX workout; the file you uploaded here had (0, 0) for all coordinates. The tracker skips those points, assuming an error.
