### ISSUE TITLE
Internal Server Error when going to Workouts page

### ISSUE THREAD

**Issue by samtate** [jovandeginste/workout-tracker#322]
The app was working great with just a few GPX but I bulk imported all my GPX from Strava and now the app crashes when I try to go to the workouts list page.

My logs from the time of the crash:
`wt-app  | {"time":"2024-11-07T12:09:46.504872802Z","level":"ERROR","msg":"Internal Server Error","app":"workout-tracker","version":"master","sha":"c6d4ea035b89edff5753043e798f0107512fc3fe","module":"webserver","request":{"time":"2024-11-07T12:09:46.262542816Z","method":"GET","host":"workouts.xxx.me.uk","path":"/workouts","query":"","params":{},"route":"/workouts","ip":"10.72.0.149","referer":"https://workouts.xxx.me.uk/","length":0},"response":{"time":"2024-11-07T12:09:46.504832617Z","latency":242289784,"status":500,"length":36},"error":{"code":500,"internal":{"Name":"workouts_list_details","Err":{}},"message":"Internal Server Error"},"internal":"template: workouts_list_details.html:12:37: executing \"workouts_list_details\" at <.Data.TotalDistance>: nil pointer evaluating *database.MapData.TotalDistance"}
wt-app  | {"time":"2024-11-07T12:09:46.630933791Z","level":"INFO","msg":"Incoming request","app":"workout-tracker","version":"master","sha":"c6d4ea035b89edff5753043e798f0107512fc3fe","module":"webserver","request":{"time":"2024-11-07T12:09:46.626798609Z","method":"GET","host":"workouts.xxx.me.uk","path":"/user/signin","query":"","params":{},"route":"/user/signin","ip":"10.72.0.149","referer":"https://workouts.xxx.me.uk/workouts","length":0},"response":{"time":"2024-11-07T12:09:46.630906269Z","latency":4107677,"status":200,"length":1547}}`

**Comment by jovandeginste** [comment]
I added a commit that should prevent this error - the data is still corrupt (probably), but now you can investigate.

If you find the problematic file and believe it is not a problem with the file, let me know: I can investigate and maybe fix the code.

**Comment by jovandeginste** [comment]
To find it, you could scratch your database and start adding them in batches; if the error returns, repeat with the last batch: scratch the database and cut the last batch in smaller parts, until you find the single (first) problematic file. Obviously, there may be more than one file with problems, but maybe they all have the same issue then?
