### ISSUE TITLE
Feature Requests: Maps + Filtering/Search

### ISSUE THREAD

**Issue by wbste** [jovandeginste/workout-tracker#335]
Hey, great app. Just what I was looking for (deployed via Docker and super lightweight), and imported all my data perfectly from what I can tell. Not sure if there's a better place than this to leave some requests; let me know.

1. Would love to be able to filter/search/sort through my data. Location, speed, and every other metric in the dashboard :) Maybe just some dropdowns in the workouts tab? By the way, the workouts tab is wicked fast for the number of workouts I have. I love it. No pagination, no other lazy loading. Just instant!
2. Adding a maps tab would be nice (but by no means necessary). Would be cool to see a map of qty of exercises by location, same style as this: https://docs.photoprism.app/developer-guide/ui/maps/. Even cooler would be heat maps once you got to a certain zoom level, but that sounds tougher.

**Comment by jovandeginste** [comment]
How would a heat map look, according to you? Dots at the center of the track that get bigger if they converge more with other center-dots?

**Comment by jovandeginste** [comment]
I made an implementation, please check it out and provide feedback!

**Comment by jovandeginste** [comment]
If you can, check out #353 (this is WIP and will trigger a number of other refactorings)

**Comment by jovandeginste** [comment]
It currently shows (partial screenshot):

![image](https://github.com/user-attachments/assets/a768452b-7572-4404-8ab9-42a13ae9b7b3)

**Comment by jovandeginste** [comment]
It's now in master branch

**Comment by jovandeginste** [comment]
(with improved tooltips!)

**Comment by jovandeginste** [comment]
It's only retrieving _your_ workouts; the case is probably that you are the only user of your installation, but the assumption is that your family or friends may use it too...

**Comment by jovandeginste** [comment]
(the heatmap is rendered client side, so caching is not easy)

**Comment by jovandeginste** [comment]
I will take more time to investigate, but I'm now working on another refactoring...
