### ISSUE TITLE
Wishlist: REST API

### ISSUE THREAD

**Issue by iotemylabs** [jovandeginste/workout-tracker#42]
I like the simplicity of this app, and I would love to see a REST API accessible on this so that I can integrate it into my Home Assistant instance, some ideas could be:
- Pull workout data
- Pull / Sync Workout calendars

Thank you, and great work!

**Comment by jovandeginste** [comment]
You can get something like a calendar with `jq` invocation:

```bash
curl -sSLf localhost:8080/api/v1/workouts -H "Authorization: Bearer YOUR_TOKEN" |
  jq '.results | map({Name: .Name, Date: .Date, Address: .Data.Address.FormattedAddress})'
```
