### ISSUE TITLE
Add option to read time from filename

### ISSUE THREAD

**Issue by el-tiuri** [jovandeginste/workout-tracker#57]
Hey, first of all very nice project! I was excited to try it, exported my activities from Strava, and promptly noticed I had a suspicious number of activities listed today. It seems like it only looks at the file modified (or created?) date, and not at the file titles. I think it might be useful to also look at file names, since exported data will often have incorrect modified dates.

**Comment by jovandeginste** [comment]
It should take the time inside the gpx file; maybe there is something missing in your exports?

**Comment by el-tiuri** [comment]
I just checked the files, there are valid and correct timestamps in them. They were converted from .tcx though, so something might have gone wrong there. I’ll retry using non-converted files, hopefully it fixes the problem.

**Comment by jovandeginste** [comment]
Okay 👍

**Comment by jovandeginste** [comment]
@el-tiuri did you get somewhere with the files?

**Comment by wills106** [comment]
I have been downloading walks / rides out of Map My Ride / Walk which is a painful process!
Then converted the tcx to gpx using Garmin BaseCamp but they are all showing as being walked today.

I am guessing it's using the <metadata> time and not the <trk> time?

I can upload a file if you want?
Perhaps there could be a toggle when importing to use first <trk> time instead of <metadata> ?

Would it be much work to support importing the tcx files directly?

**Comment by jovandeginste** [comment]
Feel free to upload a file! There were some heuristics in place to get a time, maybe there is yet another place inside the file? I don't trust the file's timestamp, and a filename is also finicky (no consistent format...)

**Comment by wills106** [comment]
[3.77mi Walk.zip](https://github.com/jovandeginste/workout-tracker/files/14898154/3.77mi.Walk.zip)
I have attached the TCX and Converted GPX in the zip

**Comment by jovandeginste** [comment]
The converter sets the time-of-conversion as the "main" time, but keeps the track time correct:

![image](https://github.com/jovandeginste/workout-tracker/assets/3170771/f78565b1-1f28-4b13-9499-a67f77fca9ae)

I'll change the code to reverse the order it gets the time...

**Comment by wills106** [comment]
I have managed to convert all / most of my previous workouts a different way now, so <time> is correct.

But I think the first track time will help others. As it makes the most logical sense that the first time recorded on the track is the start of the workout.

**Comment by jovandeginste** [comment]
@wills106 what was the converter you ended up using? I tried to implement a tcx2gpx converter for my Google Fit files, but those contained too little information to be useful. I may take it up again with your file...

**Comment by wills106** [comment]
I ended up paying £10 to use RunGap.

Imported Garmin and MapMyRide to the iPad and exported all of them back out as FIT

I still need to rename loads of them. But was a saving trying to get data out of MapMyRide, they are a nightmare to get data back out of!

I had to import 564 files from Garmin / MapMyRide.

the FitoTrack gpx Import's was the easy part!

**Comment by jovandeginste** [comment]
See #99

**Comment by wills106** [comment]
I'm not 100% happy with the conversion (Nothing to do with workout-track) I think I still have some issues with EGM84

But for historic data it can stay how it is. The main thing is that new data from FitoTrack is correct.
