### ISSUE TITLE
[Feature Request] Move some Docker Variables to Admin Page

### ISSUE THREAD

**Issue by wills106** [jovandeginste/workout-tracker#63]
Would it be possible to move the following to the admin page?
WT_REGISTRATION_DISABLED="false"
WT_SOCIALS_DISABLED="false"

This would save having to restart the Docker container.

It might also be worth having an option for each user if `WT_SOCIALS_DISABLED` is false globally, they can still disable if they wish.

This way the admin can determine if socials are allowed or not at a server level.
If socials are allowed, then a user can still remove the option to do so if they wish.

**Comment by jovandeginste** [comment]
Good idea

**Comment by jovandeginste** [comment]
Partially solved with #77 (the user-setting is implemented)
