### ISSUE TITLE
[Feature Request] Accept FitoTrack HTTP POST

### ISSUE THREAD

**Issue by wills106** [jovandeginste/workout-tracker#64]
FitoTrack has the ability to automatically export a GPX workout at the end of the workout and send it to a server.

Would it be possible to accept these requests?
I have my Workout-Tracker behind a Nginx proxy so I can securely expose Workout-Tracker to the outside world.

I think this would be a cleaner solution than exporting to a folder and then having an additional app running to export it to the server. You wouldn't need something running on the server to except file uploads either.

**Comment by jovandeginste** [comment]
I never saw that option in fitotrack; thanks for telling me about this! I'm using syncthing for this, but will look into the post! The API is now usable (to fetch statistics), adding a Post route should be easy.

**Comment by jovandeginste** [comment]
Just noticed fitotrack does not support adding headers; I'm curious if it supports basic auth in the URL...

**Comment by wills106** [comment]
I don't know if this helps, but it seems to be a relay for accepting FitTrack POST and forwarding the GPX on to Nextcloud?
https://github.com/StratusFearMe21/fittotrack-sync

**Comment by jovandeginste** [comment]
@wills106 please test and give feedback!

**Comment by wills106** [comment]
Tried single user so far and it's fine, still need to check a second user to confirm their API key redirects their workout to them and not me for example.

But I have noticed a change in the last 24hrs seems to have decoupled the start and end times for workout.

This was ok yesterday before I updated. But the speed doesn't start with the elevation.

![image](https://github.com/jovandeginste/workout-tracker/assets/18155231/fad8a635-43ee-4cb0-9eb5-0428de7e388f)

First test of the HTTP upload
![image](https://github.com/jovandeginste/workout-tracker/assets/18155231/14173948-1d7e-4611-bc19-cc6a95e96878)

Also noticed on "branch master (8175c70c" there is a bit of lag moving the mouse up and down on the workouts page.

**Comment by wills106** [comment]
> Also noticed on "branch master [8175c70](https://github.com/jovandeginste/workout-tracker/commit/8175c70cbf0a4c6bd5a18f69f350223732b3bf51)" there is a bit of lag moving the mouse up and down on the workouts page.

Just on e820e487 now and I'm still getting the Speed / Elevation mismatch.

On the workouts page you can initially move the mouse up and down and it doesn't highlight a row in the yellowish colour. It will then register on one and a few seconds later start to catch-up and highlight other rows.

**Comment by jovandeginste** [comment]
The mismatch is fixed in #121; I can't seem to reproduce the lag... Could it be related to browser?

**Comment by wills106** [comment]
Thanks, I'll test the update later today as I don't have a way to update the container at the moment.

**Comment by wills106** [comment]
Just letting you know the two graphs match up now.
Thanks

**Comment by muzzah** [comment]
Can this be used with apple workouts and the automations app? I can automatically upload a gpx file once a workout ends on my apple watch but it seems you have tied up loading a gpx file to a specific type of program? Is there an endpoint to just upload a gpx file and have it processed?

**Comment by jovandeginste** [comment]
> Can this be used with apple workouts and the automations app? I can automatically upload a gpx file once a workout ends on my apple watch but it seems you have tied up loading a gpx file to a specific type of program? Is there an endpoint to just upload a gpx file and have it processed?

I added a "generic" import path: https://github.com/jovandeginste/workout-tracker/pull/185
Could you give this a try?

**Comment by muzzah** [comment]
Nice, will update my instance and give it a run (pun not intended) and let you know

**Comment by TheBig-O** [comment]
Probably a dumb question, but would you mind sharing an example of using the API to upload/import a GPX file? I like the idea of automatically uploading a workout with the Apple Automations app, but don't want to screw things up with a bad API call.
Thanks!

**Comment by jovandeginste** [comment]
I added [some examples to the README](https://github.com/jovandeginste/workout-tracker?tab=readme-ov-file#generic-upload)

**Comment by jovandeginste** [comment]
If anything special is needed for the Apple Automations, and it might be documented here, feel free to open an issue with the relevant details (or update the README and open a PR)

**Comment by TheBig-O** [comment]
Thanks for doing that. I figured out how to get the ShortCuts app to upload the data but the file seems not be uploading. When I look at the workout, it show a little file icon with ".gpx" after it instead of the typical path that the other workouts show. Is there piece of the curl command that I'm missing? Also, is there a way to specify the name of the workout. It just posts as a no-name workout. (The data is there just fine.)
I appreciate the help on this.

**Comment by jovandeginste** [comment]
See #237
