### ISSUE TITLE
Editing workout defaults type to running

### ISSUE THREAD

**Issue by wills106** [jovandeginste/workout-tracker#68]
When editing a workout the "Type" defaults to running.
So if you don't realise you can change your workout type by mistake.
Would it be possible it reads the current "Type" and shows that as the default, that way when you "Update workout" your not changing the type, but you still have the option to do so if needed.

![image](https://github.com/jovandeginste/workout-tracker/assets/18155231/2ab7e075-bd26-4cc3-a9d7-784a67d07303)

**Comment by wills106** [comment]
Thanks, these past couple of improvements have really helped to polish up the app!

**Comment by jovandeginste** [comment]
Low hanging fruit :)
