### ISSUE TITLE
Time discrepancy

### ISSUE THREAD

**Issue by wills106** [jovandeginste/workout-tracker#75]
I have noticed a time discrepancy between the Workouts Sumary page and the timeline on the individual Workout page.

The "an hour ago" is correct. But the displayed time should be 16:18

![image](https://github.com/jovandeginste/workout-tracker/assets/18155231/37ff73d0-6023-4c44-9882-3910822d0917)

Detailed Workout page
![image](https://github.com/jovandeginste/workout-tracker/assets/18155231/aa51fd37-79ec-4bc1-8a64-1b0b93b47e12)

Timeline is correct
![image](https://github.com/jovandeginste/workout-tracker/assets/18155231/f32412ee-0dde-472e-ab72-04016bd97bd7)

Just for info the Walk started 16:18 and current time as posting is 17:58

**Comment by wills106** [comment]
The GPX does state 15:18, but I have selected London as time zone.
So it looks like the Timeline is using DST (GMT +1) but the other locations is just using GMT.

**Comment by jovandeginste** [comment]
Is it possible the timezone in your browser/on your system is not the same as the one you configured inside the web ui? The stats at the bottom are rendered in javascript, which uses the browser's timezone, while the ones in the summary and details are rendered server-side. I want to remove the dependency on javascript for this, however, but that's not ready yet.

**Comment by wills106** [comment]
Does this help?

![image](https://github.com/jovandeginste/workout-tracker/assets/18155231/d5de8d2b-aef6-4a1f-8feb-cc88799a90d9)

![image](https://github.com/jovandeginste/workout-tracker/assets/18155231/dda821de-9e99-4c9a-9d41-21a31b5a3c81)

**Comment by jovandeginste** [comment]
You can check here: https://webbrowsertools.com/timezone/

**Comment by wills106** [comment]
I used that for the second screenshot in the previous post.

**Comment by jovandeginste** [comment]
> I used that for the second screenshot in the previous post.

:facepalm: sorry :)

**Comment by jovandeginste** [comment]
Anyway, it explains the discrepancy in times shown: the timeline uses the browser time, because it's client side...

**Comment by jovandeginste** [comment]
I have tried a number of solutions so far, without luck. I'm wondering if I should drop chartjs for a different library...
