### ISSUE TITLE
[Feature Request] List duplicate start times / reject an import if duplicate start time exists.

### ISSUE THREAD

**Issue by wills106** [jovandeginste/workout-tracker#94]
Would it be possible to list all duplicated workout based on start times?

I have imported some files from Garmin connect and from MapMy Ride / Walk and I have duplicate rides/walks.
Would it be possible to highlight identical start times so I can delete one? Or when importing files check if an existing start time already exists?

**Comment by wills106** [comment]
I have merged and cleaned my workout as best as I can in another app. Deleted the Database and started from scratch.

I shouldn't get any duplicates in the future. But would still be handy if it checks the check start datetime on import.

**Comment by jovandeginste** [comment]
What should happen when such entries exist in the database? Should we just delete them...?

**Comment by wills106** [comment]
Would it be possible to see which workout contains the most meta data? Like if one contains an extra element such as heart rate to keep that. Or if one has a workout name and the other doesn't keep the one with a name?

Perhaps you could have a summary table to help you decide which to keep?

Does it contain
Heart rate: Yes / No
Power: Yes / No
Cadence: Yes / No
Workout Duration: length of time

Workout duration might be handy, as you might want to keep the shortest time as you trimmed the file down.

Do you have any plans for Heart rate / Power / Cadence in the futures? Do you have bit of a Roadmap for planned features?

**Comment by jovandeginste** [comment]
Regarding the first part: seems like a lot of work for something you should never see 😔

Regarding planned features, there is not much except improving the current state, finding edge cases, and whatever is in the TODO in the readme. I don't have any other sensors for my own workouts, so there is not much incentive for this from my side (at the moment). I would however be happy to assist if other people wanted to add the feature.

**Comment by wills106** [comment]
> seems like a lot of work for something you should never see

Your right, it's something that shouldn't really happen.
