### ISSUE TITLE
After upgraded DB workout needs to manually refreshed

### ISSUE THREAD

**Issue by miszterx** [jovandeginste/workout-tracker#98]
Hi,

I have started my activity with release version 10.5.
I have imported 5800 workouts. Worked fine.

The Next release what I used as an upgrade was 12.1. Start automatically did the upgrade. The application loads perfectly and even lists the workouts and charts. However, If I click on one particular workout for details I got:

{"message":"Internal Server Error"}

In the log I can see:

8:21PM ERR template: workouts_show.html:65:45: executing "workouts_show.html" at <.StatisticsPer>: error calling StatisticsPer: runtime error: invalid memory address or nil pointer dereference app=workout-tracker version=v0.12.3 sha=6a69273150cab3138749ee5979d462bf959e58ee module=webserver request.time="2024-04-13 20:21:34.73549021 +0200 CEST" request.method=GET

If I click on the workout list view I can make a "refresh". It fixes it.
However, I don't want to do it on more than 5000 entries.

Is there a way to trigger a refresh for all workouts? or is it a bug?
Now I tried 12.3 release as well, but it is the same.

**Comment by jovandeginste** [comment]
This seems to be a bug ...

However, you can refresh all workouts via your profile page. This will take a while, of course, and will run in the back ground. You can tail the log file to follow.

![image](https://github.com/jovandeginste/workout-tracker/assets/3170771/b5c2377f-1dd5-43b0-82df-25c734a7706d)

**Comment by miszterx** [comment]
Great! Thanks for the recommendation. So the same is responsible for the bulk refresh as well.
Just triggered. Thanks for the solution. 

Not sure about the startup process, when it detects the DB needs to be upgraded, but probably a step is missing there.

**Comment by miszterx** [comment]
fixed with workaround

**Comment by jovandeginste** [comment]
Database migrations are hard... But the workaround should help!
